services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    build:
      context: .
      target: api
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - DB_HOST=db
      - ALLOWED_HOSTS=localhost,127.0.0.1
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  ng:
    build:
      context: .
      target: ng
    ports:
      - "8001:80"
    depends_on:
      - api

volumes:
  postgres_data:
